# Generated by Django 4.2.1 on 2023-05-19 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_female', models.BooleanField(blank=True, null=True)),
                ('is_male', models.BooleanField(blank=True, null=True)),
                ('age_from', models.CharField(max_length=100)),
                ('age_to', models.CharField(max_length=100)),
                ('treatment', models.CharField(blank=True, max_length=2000, null=True)),
                ('prophylaxis', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('flag', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.symptom')),
            ],
        ),
    ]
